### ISSUE TITLE
Error: Could not load...

### ISSUE THREAD

**Issue by Xastabus** [MoriyaShiine/respawnable-pets#14]
I attempted to add this plugin to my server. The plugin failed to load.

`[12:49:02] [Server thread/ERROR]: Could not load 'plugins/respawnablepets-1.1.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml`

**Comment by MoriyaShiine** [comment]
This isn't a plugin, it's a mod. It only works on Minecraft Forge.

**Comment by Xastabus** [comment]
Sorry, I must have misfiled it when I was downloading a lot of things for a new server build. My mistake.
